---
title: Minimal Mistakes
timezone: UTC
collections:
  pets:
    title: Pets
    output: true
    permalink: "/:collection/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: recipes
  values:
    layout: single
    author_profile: true
    share: true
- scope:
    path: ''
    type: pets
  values:
    layout: single
    author_profile: true
    share: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: false
    share: true
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: contrast
locale: en-US
title_separator: "-"
subtitle: Development Test Site
name: Your Name
description: Minimal Mistakes theme test.
url: 
baseurl: ''
repository: vcapillo/vcapillo.github.io
teaser: 
logo: "/assets/images/apple-touch-icon.png"
masthead_title: Custom Title
words_per_minute: 200
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
  utterances:
    theme: 
    issue_term: 
  giscus:
    repo_id: 
    category_name: 
    category_id: 
    discussion_term: 
    reactions_enabled: 
    theme: 
  staticman:
    branch: 
    endpoint: 
atom_feed:
  path: 
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true
algolia:
  application_id: QB6HVGBSBA
  index_name: dev_minimal-mistakes
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: true
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
twitter:
  username: mmistakes
facebook:
  username: 
  app_id: 
  publisher: 
og_image: "/assets/images/bio-photo.jpg"
social:
  type: 
  name: 
  links:
  - https://twitter.com/
  - https://github.com/
analytics:
  provider: false
  google:
    tracking_id: 
author:
  name: Your Name
  avatar: "/assets/images/bio-photo.jpg"
  bio: I am an **amazing** person.
  location: Somewhere
  links:
  - label: Your Website
    icon: fas fa-fw fa-link
    url: https://your-site.com
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: true
liquid:
  error_mode: strict
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
