---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Victor Capillo
url: https://vcapillo.github.io/
description: 'Moonwalk is a fast and elegant Jekyll theme with a clean dark mode.
  It comes with horizontal list (for navbar and footer), card list (for portfolio),
  and a generic vertical list. It is very easy to modify in case you want to build
  over it - please see _layouts/home.html to do that.

'
permalink: "/:slug"
favicon: "./logo.png"
twitter:
  username: abhinav
  card: summary_large_image
remote_theme: abhinavs/moonwalk
theme_config:
  appearance: dark
  back_home_text: go back..
  appearance_toggle: true
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_old_projects: true
  show_misc_list: false
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects
soopr:
  publish_token: ''
highlighter: rouge
sass:
  style: :compressed
plugins:
- jekyll-feed
- jekyll-seo-tag
