backend:
  name: github
  repo: vcapillo/vcapillo.github.io # Path to your GitHub repository  
  branch: master
  site_domain: blog.alias.nom.pe
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de Publicación', name: 'date', widget: 'datetime' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.markdown'
        fields:
          - { label: 'Título', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Contenido', name: 'body', widget: 'markdown' }