backend:
  name: git-gateway
  #repo: vcapillo/vcapillo.github.io # Path to your GitHub repository  
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }