backend:
  name: github
  repo: vcapillo/vcapillo.github.io # Path to your GitHub repository
  # optional, defaults to master
  # branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }